version: '3'
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks: 
      - directus
      - foundry
      - nextcloud

  cache:
    image: redis:6
    restart: unless-stopped
    networks:
      - directus

  directus:
    image: directus/directus:latest
    restart: unless-stopped
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      - ./database:/directus/database
      # If you want to load extensions from the host
      - ./extensions:/directus/extensions
      - ./cred:/directus/cred
    networks:
      - directus
    depends_on:
      - cache
    environment:
      KEY: 'e52308e1-3f0c-4de8-b3ec-7a7923a0aeff'
      SECRET: ${DIRECTUS_SECRET}

      DB_CLIENT: 'sqlite3'
      DB_FILENAME: '/directus/database/directus-cms.sqlite'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'
      CACHE_AUTO_PURGE: true

      ADMIN_EMAIL: '${DIRECTUS_ADMIN_EMAIL}'
      ADMIN_PASSWORD: '${DIRECTUS_ADMIN_PASSWORD}'

      STORAGE_LOCATIONS: "gcs"
      STORAGE_GCS_DRIVER: "gcs"
      STORAGE_GCS_ROOT: "cms"
      STORAGE_GCS_BUCKET: "${G_CLOUD_BUCKET}"
      STORAGE_GCS_KEY_FILENAME: "/directus/${G_CLOUD_KEYFILE_PATH}"

      # Make sure to set this in production
      # (see https://docs.directus.io/configuration/config-options/#general)
      # PUBLIC_URL: 'https://cms.ephriamhenderson.dev'

  # Foundry
  foundry:
    image: felddy/foundryvtt:release
    restart: unless-stopped
    hostname: my_foundry_host
    init: true
    volumes:
      - ./foundry/data:/data
    environment:
      FOUNDRY_USERNAME: ${FOUNDRY_USERNAME}
      FOUNDRY_PASSWORD: ${FOUNDRY_PASSWORD}
      FOUNDRY_ADMIN_KEY: ${FOUNDRY_ADMIN_KEY}
    ports:
      - 30000:30000
    networks:
      - foundry 
  
  nextcloud-db:
    image: mariadb:10.6
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ./nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_DB_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - nextcloud

  nextcloud:
    image: nextcloud
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./nextcloud/data:/var/www/html
    environment:
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.ephriamhenderson.dev
    networks:
      - nextcloud

  

networks:
  directus:
  foundry:
  nextcloud:

volumes:
  caddy_data:
    external: true
  caddy_config: